language: node_js
node_js:
  - stable
cache: yarn
env:
  global:
    secure: NyF+gNWB9ztRh3JMGK7tBk6NvYnp8VhXU/qOkbKOmwO4TPHnx/4Rz7aKNc5B0ag4j3JU9/Jkdki0tgmohyhkvFvDBRwYwpqk2J57rBbM4k6rhtej5vsND1q6dfOoxeMWSR3gM0KXcXmHjfqFtBWsEKXDuH2ipUa2ms+R5813mLaFC3snK+4GihT8w3Dv7YYZTBd2H2KCrlIv85fqmSw2Tk2KVxZyVX1/ZRxnai9p6hRuj6R/jfiBg2UpVlZ4hvMXjiOZ+mtct9Gn6nV+4DvidFyLYNX1nvk985UXiTQ5PykLk+fb4S2VxbGBexitw6/hUq6blUXgQTwomThcgDPl0wNNeQuXFuahJUhqwXPqVbCe06SFn/dR7zdcQnvTJ+AOxEi7B657qHdpMPROD898snpmsVJooYvmaSsp2sNWgCn+YubgfQsoxpTwxZ0xqr/zcy/gd1TMAwrUXybV+RAZfvYzsu4u4WNMi8XgZQAhPOzDRpHjceQDxgNXNFLRx5HIr1jgvxRyANpC0ahf+m7+9ikWrSwctbeXcFS45ycWVRoioUexQNm/ptboY+Vs5irsMEsEccacPdk8qKkiMDCSovBcVDgaAjy3DceAdQ1cOBBvAgTpd6kAQZnq+6ceLyQ5Xd38S5QEYGv0DZUVls2klO6DJ15aB76bYTRZiNzXe04=
before_script:
  - yarn global add firebase-tools
script:
  - yarn test
  - yarn build
  - ls dist
after_success:
  - firebase deploy --token $secure
branches:
  only:
    - master
