language: node_js
node_js:
  - v10.16.0
cache: yarn
env:
  global:
    secure: CaVelNV1NriF8+RJLj0aKQnxoCQFKCvW0mnA4okfnxCHzDIQ+3e4mrKx+D+wTmSbhGDsEH4U5WGHmwaqSgOM3ovZguvgx8hcUp9S7hWhOEphsgsQ+CFF3MiI+14g5xGx0RjI7HG1XoUNbBGMqU5FumCgi+e0sJhE/jwZtGrjH+Mg1R2az931STowOTVpKbjkUhNxk2QA7p8ZDK3Uqv4WLDYetIkkRU1bNJIQF6yp1Ip5kh630O60HOOMCrUS15ZSloEUDhAad3BaePERGcS40F9yaMG8a/nKZerh4mdOD7LVEZ4/Gd2bTO4tZPgJd5s4ggv6I2PHYTfWL9sjRAYMlantNA/pPCJ9rR9MKGgaxM4N7Zxha7VA2LFASKEWBa0k2E7KL+ObJM5HtlEYrRCLX9Bne5nIiDPNmLS7oqhhqYS4/ISGdvyy0Sujn79kCeNm08kbstgH/wNlZWrUeFBpSEsPmDWdC98qYzW0URghDFPTXyoutEuF4WK8XRs1N/OmPn2Vw+9E2aFwb/CsuiVDXX9Xr1syR4JnK6kFulD2FaJxQLHmQqbBLLkZ4A3NsAHVv1NGW0KeYL4MtWhC/xftzUCyQxf01olNRzhXYr4Mg52F2PEwQfG9xa0vL6V06a0+GTlZ7og3uK0RauwMjbu70aCOHh+ri9u9zQyRYMA3/Go=
before_deploy:
  - yarn global add firebase-tools
  - yarn build
deploy:
  provider: firebase
  token:
    secure: CaVelNV1NriF8+RJLj0aKQnxoCQFKCvW0mnA4okfnxCHzDIQ+3e4mrKx+D+wTmSbhGDsEH4U5WGHmwaqSgOM3ovZguvgx8hcUp9S7hWhOEphsgsQ+CFF3MiI+14g5xGx0RjI7HG1XoUNbBGMqU5FumCgi+e0sJhE/jwZtGrjH+Mg1R2az931STowOTVpKbjkUhNxk2QA7p8ZDK3Uqv4WLDYetIkkRU1bNJIQF6yp1Ip5kh630O60HOOMCrUS15ZSloEUDhAad3BaePERGcS40F9yaMG8a/nKZerh4mdOD7LVEZ4/Gd2bTO4tZPgJd5s4ggv6I2PHYTfWL9sjRAYMlantNA/pPCJ9rR9MKGgaxM4N7Zxha7VA2LFASKEWBa0k2E7KL+ObJM5HtlEYrRCLX9Bne5nIiDPNmLS7oqhhqYS4/ISGdvyy0Sujn79kCeNm08kbstgH/wNlZWrUeFBpSEsPmDWdC98qYzW0URghDFPTXyoutEuF4WK8XRs1N/OmPn2Vw+9E2aFwb/CsuiVDXX9Xr1syR4JnK6kFulD2FaJxQLHmQqbBLLkZ4A3NsAHVv1NGW0KeYL4MtWhC/xftzUCyQxf01olNRzhXYr4Mg52F2PEwQfG9xa0vL6V06a0+GTlZ7og3uK0RauwMjbu70aCOHh+ri9u9zQyRYMA3/Go=
  on:
    branch: master
